// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyNhaHang.Models;

#nullable disable

namespace QuanLyNhaHang.Migrations
{
    [DbContext(typeof(QuanLyNhaHangContext))]
    partial class QuanLyNhaHangContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyNhaHang.Models.BoPhan", b =>
                {
                    b.Property<string>("MaBoPhan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenBoPhan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("TienCong")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaBoPhan");

                    b.ToTable("BO_PHAN");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.ChiTietCombo", b =>
                {
                    b.Property<string>("MaChiTietCombo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaComboMon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaMonAn")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaChiTietCombo");

                    b.HasIndex("MaComboMon");

                    b.HasIndex("MaMonAn");

                    b.ToTable("CHI_TIET_COMBO");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.ChiTietThucDon", b =>
                {
                    b.Property<string>("MaChiTietThucDon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GhiChuThem")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaDatTiec")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaMonAn")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("SoLuongMotBan")
                        .HasColumnType("int");

                    b.HasKey("MaChiTietThucDon");

                    b.HasIndex("MaDatTiec");

                    b.HasIndex("MaMonAn");

                    b.ToTable("CHI_TIET_THUC_DON");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.ComboMon", b =>
                {
                    b.Property<string>("MaComboMon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("GiaCombo")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("HinhAnhCombo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayTaoCombo")
                        .HasColumnType("date");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenCombo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaComboMon");

                    b.ToTable("COMBO_MON");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.DatTiec", b =>
                {
                    b.Property<string>("MaDatTiec")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ChiTiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GiaBan")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<TimeSpan?>("GioToChuc")
                        .HasColumnType("time");

                    b.Property<string>("MaKhachHang")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgayDatTiec")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayToChuc")
                        .HasColumnType("date");

                    b.Property<int?>("SoBanDat")
                        .HasColumnType("int");

                    b.Property<string>("TenChuRe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenCoDau")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("TienCoc")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaDatTiec");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("DAT_TIEC");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.DichVu", b =>
                {
                    b.Property<string>("MaDichVu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GiaDV")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("HinhAnhDichVu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaDV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDichVu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThaiDV")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaDichVu");

                    b.ToTable("DICH_VU");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.HinhAnh", b =>
                {
                    b.Property<string>("MaHinhAnh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDichVu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaMonAn")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrangThaiHinhAnh")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHinhAnh");

                    b.HasIndex("MaDichVu");

                    b.HasIndex("MaMonAn");

                    b.ToTable("HINH_ANH");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.KhachHang", b =>
                {
                    b.Property<string>("MaKhachHang")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CccdKhachHang")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("DiaChiKhachHang")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaTaiKhoan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SdtKhachHang")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenKhachHang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThaiKhachHang")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaKhachHang");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("KHACH_HANG");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.MonAn", b =>
                {
                    b.Property<string>("MaMonAn")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("DonViTinh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnhMonAn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiMonAn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTaMonAn")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenMonAn")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThaiMonAn")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaMonAn");

                    b.ToTable("MON_AN");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CccdNV")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ChucVuNV")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DiaChiNV")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaBoPhan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaTaiKhoan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SdtNV")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenNhanVien")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThaiNV")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("MaBoPhan");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("NHAN_VIEN");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.PasswordResetToken", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Token");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.PhieuThanhToan", b =>
                {
                    b.Property<string>("MaPhieu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDatTiec")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaPhieu");

                    b.HasIndex("MaDatTiec")
                        .IsUnique();

                    b.ToTable("PHIEU_THANH_TOAN");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.TT_SuDungDichVu", b =>
                {
                    b.Property<string>("MaThongTinDV")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDatTiec")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaDichVu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgaySuDung")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaThongTinDV");

                    b.HasIndex("MaDatTiec");

                    b.HasIndex("MaDichVu");

                    b.ToTable("TT_SU_DUNG_DICH_VU");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.TT_SuDungNhanVien", b =>
                {
                    b.Property<string>("MaThongTinNV")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDatTiec")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaNhanVien")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaThongTinNV");

                    b.HasIndex("MaDatTiec");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("TT_SU_DUNG_NHAN_VIEN");
                });

<<<<<<< HEAD
            modelBuilder.Entity("QuanLyNhaHang.Models.TaiKhoan", b =>
                {
                    b.Property<string>("MaTaiKhoan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UserName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("VaiTro")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaTaiKhoan");

                    b.ToTable("TAI_KHOAN");
                });

=======
>>>>>>> 03c721d578e498f3bfe8ffced87e4f47b8796137
            modelBuilder.Entity("QuanLyNhaHang.Models.ChiTietCombo", b =>
                {
                    b.HasOne("QuanLyNhaHang.Models.ComboMon", "ComboMon")
                        .WithMany("ChiTietCombos")
                        .HasForeignKey("MaComboMon");

                    b.HasOne("QuanLyNhaHang.Models.MonAn", "MonAn")
                        .WithMany()
                        .HasForeignKey("MaMonAn");

                    b.Navigation("ComboMon");

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.ChiTietThucDon", b =>
                {
                    b.HasOne("QuanLyNhaHang.Models.DatTiec", "DatTiec")
                        .WithMany("ChiTietThucDons")
                        .HasForeignKey("MaDatTiec");

                    b.HasOne("QuanLyNhaHang.Models.MonAn", "MonAn")
                        .WithMany("ChiTietThucDons")
                        .HasForeignKey("MaMonAn");

                    b.Navigation("DatTiec");

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.DatTiec", b =>
                {
                    b.HasOne("QuanLyNhaHang.Models.KhachHang", "KhachHang")
                        .WithMany("DatTiecs")
                        .HasForeignKey("MaKhachHang");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.HinhAnh", b =>
                {
                    b.HasOne("QuanLyNhaHang.Models.DichVu", "DichVu")
                        .WithMany()
                        .HasForeignKey("MaDichVu");

                    b.HasOne("QuanLyNhaHang.Models.MonAn", "MonAn")
                        .WithMany()
                        .HasForeignKey("MaMonAn");

                    b.Navigation("DichVu");

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.KhachHang", b =>
                {
                    b.HasOne("QuanLyNhaHang.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTaiKhoan");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.NhanVien", b =>
                {
                    b.HasOne("QuanLyNhaHang.Models.BoPhan", "BoPhan")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaBoPhan");

                    b.HasOne("QuanLyNhaHang.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTaiKhoan");

                    b.Navigation("BoPhan");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.PhieuThanhToan", b =>
                {
                    b.HasOne("QuanLyNhaHang.Models.DatTiec", "DatTiec")
                        .WithOne("PhieuThanhToan")
                        .HasForeignKey("QuanLyNhaHang.Models.PhieuThanhToan", "MaDatTiec")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatTiec");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.TT_SuDungDichVu", b =>
                {
                    b.HasOne("QuanLyNhaHang.Models.DatTiec", "DatTiec")
                        .WithMany("TT_SuDungDichVus")
                        .HasForeignKey("MaDatTiec");

                    b.HasOne("QuanLyNhaHang.Models.DichVu", "DichVu")
                        .WithMany("TT_SuDungDichVus")
                        .HasForeignKey("MaDichVu");

                    b.Navigation("DatTiec");

                    b.Navigation("DichVu");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.TT_SuDungNhanVien", b =>
                {
                    b.HasOne("QuanLyNhaHang.Models.DatTiec", "DatTiec")
                        .WithMany("TT_SuDungNhanViens")
                        .HasForeignKey("MaDatTiec");

                    b.HasOne("QuanLyNhaHang.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien");

                    b.Navigation("DatTiec");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.BoPhan", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.ComboMon", b =>
                {
                    b.Navigation("ChiTietCombos");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.DatTiec", b =>
                {
                    b.Navigation("ChiTietThucDons");

                    b.Navigation("PhieuThanhToan")
                        .IsRequired();

                    b.Navigation("TT_SuDungDichVus");

                    b.Navigation("TT_SuDungNhanViens");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.DichVu", b =>
                {
                    b.Navigation("TT_SuDungDichVus");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.KhachHang", b =>
                {
                    b.Navigation("DatTiecs");
                });

            modelBuilder.Entity("QuanLyNhaHang.Models.MonAn", b =>
                {
                    b.Navigation("ChiTietThucDons");
                });
#pragma warning restore 612, 618
        }
    }
}
